project_id = "xaypooqwcrhytkfqyzha"

[functions.validate-phone-numbers]
verify_jwt = true

[functions.smart-contact-import]
verify_jwt = true

[functions.inbox-send-text]
verify_jwt = false

[functions.inbox-send-template]
verify_jwt = false

[functions.campaign-process-queue]
verify_jwt = false

[functions.webhook-notificame]
verify_jwt = false
