project_id = "xaypooqwcrhytkfqyzha"

[functions.validate-phone-numbers]
verify_jwt = true

[functions.whatsapp-session]
verify_jwt = true

[functions.send-whatsapp-messages]
verify_jwt = true

[functions.uazapi-webhook]
verify_jwt = false

[functions.smart-contact-import]
verify_jwt = true

[functions.send-single-message]
verify_jwt = true
